/**
 * Charging state of electric vehicle
 */
export enum ChargingState {
  CHARGING = 'CHARGING',
  ERROR = 'ERROR',
  FINISHED_FULLY_CHARGED = 'FINISHED_FULLY_CHARGED',
  FINISHED_NOT_FULL = 'FINISHED_NOT_FULL',
  INVALID = 'INVALID',
  NOT_CHARGING = 'NOT_CHARGING',
  WAITING_FOR_CHARGING = 'WAITING_FOR_CHARGING'
}
