export enum ServiceType {
  CHARGE_NOW = 'CHARGE_NOW',
  CLIMATE_NOW = 'CLIMATE_NOW',
  DOOR_LOCK = 'DOOR_LOCK',
  DOOR_UNLOCK = 'DOOR_UNLOCK',
  LIGHT_FLASH = 'LIGHT_FLASH',
  CHARGING_CONTROL = 'CHARGING_CONTROL',
  CLIMATE_CONTROL = 'CLIMATE_CONTROL'
}
